<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('debardeurs', function (Blueprint $table) {
            $table->id();
            $table->foreignId('province_id')->constrained()->cascadeOnDelete();
            $table->string('sector'); // Routier, Lacustre, Aérien, Ferroviaire

            // Personal Information
            $table->string('last_name'); // Noms
            $table->string('middle_name')->nullable(); // Post-nom
            $table->string('first_name'); // Prénom
            $table->string('birth_place');
            $table->date('birth_date')->nullable();
            $table->string('gender'); // Sexe
            $table->string('father_name');
            $table->string('mother_name');
            $table->string('marital_status'); // Etat-civil
            $table->string('nationality')->default('Congolaise');

            // Identity Documents
            $table->string('id_type')->default("Carte d'électeur");
            $table->string('id_number');
            $table->date('id_expiration_date')->nullable();

            // Migratory Documents (for foreigners)
            $table->string('migratory_doc_type')->nullable();
            $table->string('migratory_doc_number')->nullable();

            // Assignment & Professional info
            $table->string('profession');
            $table->string('assignment_place'); // Lieu d'affectation
            $table->string('association_cooperative')->nullable();
            $table->string('member_card_number')->nullable();
            $table->string('vest_number')->nullable(); // Numéro du gilet

            // Contact info
            $table->string('phone');
            $table->text('residence_address');

            // System fields
            $table->string('permanent_number')->unique(); // Generated by system

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('debardeurs');
    }
};
